modLoader="javafml"
loaderVersion="[35,)"

license="All rights reserved"

issueTrackerURL="https://github.com/KeystoneTeam/KeystoneEditor/issues"
updateJSONURL="https://github.com/KeystoneTeam/KeystoneEditor/raw/master/update.json"
displayURL="https://github.com/KeystoneTeam/KeystoneEditor/releases"
#logoFile="keystone.png"

[[mods]]
modId="keystone" #mandatory
version="${file.jarVersion}"
displayName="Keystone Editor"

credits="Based off of MCEdit Unified" #optional
authors="CodeCracked" #optional
description='''
A mod which turns the game into a powerful map editor with similar features to MCEdit Unified.
'''

[[dependencies.keystone]]
    modId="forge"
    mandatory=true
    versionRange="[35,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.keystone]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4,1.17)"
    ordering="NONE"
    side="BOTH"
