modLoader="javafml"
loaderVersion="[35,)"

license="All rights reserved"

#issueTrackerURL="http://my.issue.tracker/" #optional
#updateJSONURL="http://myurl.me/" #optional
#displayURL="http://example.com/" #optional
#logoFile="keystone.png" #optional

[[mods]]
modId="keystone" #mandatory
version="${file.jarVersion}"
displayName="Keystone Editor"

credits="CodeCracked" #optional
authors="CodeCracked" #optional
description='''
A mod which turns the game into a powerful map editor with similar features to MCEdit Unified.
'''

[[dependencies.keystone]]
    modId="forge" #mandatory
    mandatory=true
    versionRange="[35,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.keystone]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4,1.17)"
    ordering="NONE"
    side="BOTH"
