modLoader="javafml"
loaderVersion="[35,)"

license="GPL v3.0"

issueTrackerURL="https://github.com/KeystoneTeam/KeystoneEditor/issues"
displayURL="https://github.com/KeystoneTeam/KeystoneEditor/releases"
logoFile="keystone.png"

[[mods]]
modId="keystone" #mandatory
version="${version_keystone}"
displayName="Keystone Editor"
updateJSONURL="https://github.com/KeystoneTeam/KeystoneEditor/raw/master/update.json"

credits="Based off of MCEdit Unified" #optional
authors="CodeCracked" #optional
description='''
    Keystone, a powerful world editing mod based off of MCEdit Unified'''

[[dependencies.keystone]]
    modId="forge"
    mandatory=true
    versionRange="[${version_forge},)"
    ordering="NONE"
    side="BOTH"
[[dependencies.keystone]]
    modId="minecraft"
    mandatory=true
    versionRange="[${min_version_minecraft},${max_version_minecraft})"
    ordering="NONE"
    side="BOTH"
