modLoader="javafml"
loaderVersion="[35,)"

license="GPL v3.0"

issueTrackerURL="https://github.com/KeystoneTeam/KeystoneEditor/issues"
updateJSONURL="https://github.com/KeystoneTeam/KeystoneEditor/raw/master/update.json"
displayURL="https://github.com/KeystoneTeam/KeystoneEditor/releases"
logoFile="keystone.png"

[[mods]]
modId="keystone" #mandatory
version="${file.jarVersion}"
displayName="Keystone Editor"

credits="Based off of MCEdit Unified" #optional
authors="CodeCracked" #optional
description='''
    Keystone, a powerful world editing mod based off of MCEdit Unified'''

[[dependencies.keystone]]
    modId="forge"
    mandatory=true
    versionRange="[35,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.keystone]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4,1.17)"
    ordering="NONE"
    side="BOTH"
